[package]
name = "subquote"
version = "0.1.0"
authors = ["beurre <zidronfirefax@gmail.com>"]
edition = "2018"

[dependencies]
getopts = "0.2.21"
regex = "1.3.1"
serde = { version = "1.0.103", features = ["derive"] }
serde_json = "1.0.42"
rand = "0.7.2"